# Generated by Django 6.1.1 on 2026-09-15 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure in mmHg', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure in mmHg', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, help_text='Pulse rate in beats per minute', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, help_text='Blood sugar in mg/dL', max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='triage', to='encounters.encounter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
