# Generated by Django 6.1.1 on 2026-09-15 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('chief_complaint', models.TextField(blank=True, help_text='Main reason the patient came to the clinic')),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True, help_text="Doctor's clinical assessment")),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='encounters.encounter')),
            ],
        ),
    ]
