# Generated by Django 6.1.1 on 2026-09-16 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('result', models.TextField()),
                ('notes', models.TextField(blank=True, help_text='Additional laboratory notes or comments.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=20)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_result', to='orders.clinicalorder')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
