# Generated by Django 6.1.1 on 2026-09-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Commercial or displayed medication name', max_length=200)),
                ('generic_name', models.CharField(blank=True, help_text='Generic/active ingredient name', max_length=200)),
                ('strength', models.CharField(blank=True, help_text='Example: 500 mg or 250 mg/5 mL', max_length=100)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('unit', models.CharField(default='unit', help_text='Example: tablet, capsule, bottle, tube', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
