# Generated by Django 6.1.1 on 2026-09-19 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_stockbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('DISPENSE', 'Dispense'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock added, negative for stock removed')),
                ('reference', models.CharField(blank=True, help_text='Related document, prescription, invoice, adjustment number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pharmacy.medication')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockbatch')),
            ],
        ),
    ]
