# Generated by Django 6.1.1 on 2026-09-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
