# Generated by Django 6.1.1 on 2026-09-15 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('encounters', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('RESULT_AVAILABLE', 'Result Available'), ('DOCTOR_REVIEWED', 'Doctor Reviewed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price captured at the time of ordering, in ETB', max_digits=10)),
                ('clinical_notes', models.TextField(blank=True, help_text='Instructions or notes from the ordering doctor')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_orders', to='consultations.consultation')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_orders', to='encounters.encounter')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_orders', to='services.service')),
            ],
        ),
    ]
